#!/bin/bash

WD_ROOT=".wd"
WD_DIRS="dirs"
WD_FULL_PATH="$HOME/$WD_ROOT/$WD_DIRS"
WD_COMMANDS="help save rename remove rm list ls"

LIST_FLAGS="--sort"
SORT_ARGS="alias target"
BAD_CHARACTERS=". / ~ \\"

ERROR_KIND__ALIAS_NOT_PROVIDED="ALIAS_NOT_PROVIDED"
ERROR_KIND__ALIAS_NOT_EXIST="ALIAS_NOT_EXIST"
ERROR_KIND__ALIAS_ALREADY_EXIST="ALIAS_ALREADY_EXIST"
ERROR_KIND__ALIAS_NOT_ALLOWED_KEYWORD_RESERVED="ALIAS_NOT_ALLOWED_KEYWORD_RESERVED"
ERROR_KIND__ALIAS_NOT_ALLOWED_NAME_MALFORMED="ALIAS_NOT_ALLOWED_NAME_MALFORMED"
ERROR_KIND__COMMAND_FLAG_NOT_SUPPORTED="COMMAND_FLAG_NOT_SUPPORTED"
ERROR_KIND__FLAG_SORT_MISSING_ARGUMENT="FLAG_SORT_MISSING_ARGUMENT"

generate_error() {
    local message=""
    case $1 in
    $ERROR_KIND__ALIAS_NOT_PROVIDED)
        message="alias not provided"
        ;;
    $ERROR_KIND__ALIAS_NOT_EXIST)
        message="alias does not exist"
        ;;
    $ERROR_KIND__ALIAS_ALREADY_EXIST)
        message="alias already exist"
        ;;
    $ERROR_KIND__ALIAS_NOT_ALLOWED_KEYWORD_RESERVED)
        shift 1
        message="alias not allowed, keywords [ $* ] are reserved"
        ;;
    $ERROR_KIND__ALIAS_NOT_ALLOWED_NAME_MALFORMED)
        shift 1
        message="alias not allowed, characters [ $* ] may not be in the name"
        ;;
    $ERROR_KIND__COMMAND_FLAG_NOT_SUPPORTED)
        shift 1
        message="flag not supported, provide one of [ $* ]"
        ;;
    $ERROR_KIND__FLAG_SORT_MISSING_ARGUMENT)
        shift 1
        message="missing flag argument, provide one of [ $* ]"
        ;;
    *)
        message="undefined error"
        ;;
    esac
    unset_everything
    echo $message 1>&2
    return 1
}

join_list_on() {
    local IFS=$1
    shift 1
    echo "$*"
}

get_entries() {
    local entries=""
    while read -r "entry"; do
        entries+="$entry\n"
    done < $WD_FULL_PATH
    echo -e $entries
}

print_entry_alias() {
    echo "$1" | awk -F "|" '{print $1}'
}

print_entry_target() {
    echo "$1" | awk -F "|" '{print $2}'
}

find_entry_by_alias() {
    local val=""
    for entry in $(get_entries); do
        local alias=$(print_entry_alias "$entry")
        if [ "$1" == "$alias" ]; then
            val=$entry
            break
        fi
    done
    echo $val
}

alias_exist() {
    local entry=$(find_entry_by_alias $1)
    if [ "$entry" != "" ]; then
        echo 1
    else
        echo 0
    fi
}

contains_bad_characters() {
    local is_bad=0
    for c in $BAD_CHARACTERS; do
        case $1 in
            *$c*)
                is_bad=1
                break
                ;;
        esac
    done
    echo $is_bad
}

is_reserved_keyword() {
    local reserved=0
    for cmd in $WD_COMMANDS; do
        if [ "$1" == "$cmd" ]; then
            reserved=1
            break
        fi
    done
    echo $reserved
}

goto_alias_target() {
    local entry=$(find_entry_by_alias $1)
    if [ "$entry" != "" ]; then
        local target=$(print_entry_target "$entry")
        if [ "$PWD" != "$(realpath $target)" ]; then
            WD_PREV_PWD_OLD="$PWD"
            WD_PREV_PWD_NEW="$(realpath $target)"
        fi
        cd $target
    fi
}

handle_remove() {
    local wd_prompted=1
    local filtered_entries=""
    while [ $wd_prompted -eq 1 ]; do
        read -p "are you sure you want to remove alias [ $1 ]? (N/y) " user_input
        if [ "$user_input" == "" -o "$user_input" == "n" -o "$user_input" == "N" ]; then
            echo "nothing changed"
            wd_prompted=0
        elif [ "$user_input" == "y" -o "$user_input" == "Y" ]; then
            for entry in $(get_entries); do
                local alias=$(print_entry_alias "$entry")
                if [ "$1" != "$alias" ]; then
                    filtered_entries+="$entry "
                fi
            done
            if [ "$filtered_entries" ]; then
                local IFS=" "
                echo $(join_list_on $'\n' $filtered_entries) > $WD_FULL_PATH
            else
                echo -n "" > $WD_FULL_PATH
            fi
            wd_prompted=0
        fi
    done
}

handle_rename() {
    local filtered_entries=""
    for entry in $(get_entries); do
        local alias=$(print_entry_alias "$entry")
        local target=$(print_entry_target "$entry")
        if [ "$1" == "$alias" ]; then
            filtered_entries+="$2|$target "
        else
            filtered_entries+="$entry "
        fi
    done
    local IFS=" "
    echo $(join_list_on $'\n' $filtered_entries) > $WD_FULL_PATH
}

handle_list() {
    local table_header="Alias|Target\n-----|------\n"
    local raw_table="$table_header$(get_entries)"
    if [ $1 ]; then
        if [ "$1" == "--sort" ]; then
            case $2 in
            "alias")
                echo -e "$raw_table" | awk 'NR<=2{print;next}{print | "sort -t\"|\" -k1"}'
                ;;
            "target")
                echo -e "$raw_table" | awk 'NR<=2{print;next}{print | "sort -t\"|\" -k2"}'
                ;;
            *)
                echo "E_ARG"
                ;;
            esac
        else
            echo "E_FLAG"
        fi
    else
        echo -e "$raw_table"
    fi
}

unset_everything() {
    unset WD_SCRIPT_SELF_DIR WD_ROOT WD_DIRS LIST_FLAGS SORT_ARGS BAD_CHARACTERS ERROR_KIND__ALIAS_NOT_PROVIDED ERROR_KIND__ALIAS_NOT_EXIST ERROR_KIND__ALIAS_ALREADY_EXIST ERROR_KIND__ALIAS_NOT_ALLOWED_KEYWORD_RESERVED ERROR_KIND__ALIAS_NOT_ALLOWED_NAME_MALFORMED ERROR_KIND__COMMAND_FLAG_NOT_SUPPORTED ERROR_KIND__FLAG_SORT_MISSING_ARGUMENT generate_error join_list_on get_entries print_entry_alias print_entry_target find_entry_by_alias alias_exist contains_bad_characters is_reserved_keyword goto_alias_target handle_remove handle_rename handle_list cmd entries_table
}
