#!/bin/bash

export WD_PREV_PWD=("" "$HOME")
WD_ROOT=".wd"
WD_DIRS="dirs"
WD_FULL_PATH="$HOME/$WD_ROOT/$WD_DIRS"
WD_COMMANDS=("help" "save" "rename" "remove" "list")

BAD_CHARACTERS=("." '/')
ERROR_KIND__ALIAS_NOT_PROVIDED="ALIAS_NOT_PROVIDED"
ERROR_KIND__ALIAS_NOT_EXIST="ALIAS_NOT_EXIST"
ERROR_KIND__ALIAS_ALREADY_EXIST="ALIAS_ALREADY_EXIST"
ERROR_KIND__ALIAS_NOT_ALLOWED_KEYWORD_RESERVED="ALIAS_NOT_ALLOWED_KEYWORD_RESERVED"
ERROR_KIND__ALIAS_NOT_ALLOWED_NAME_MALFORMED="ALIAS_NOT_ALLOWED_NAME_MALFORMED"

generate_error() {
    local message=""
    case $1 in
    $ERROR_KIND__ALIAS_NOT_PROVIDED)
        message="alias not provided"
        ;;
    $ERROR_KIND__ALIAS_NOT_EXIST)
        message="alias does not exist"
        ;;
    $ERROR_KIND__ALIAS_ALREADY_EXIST)
        message="alias already exist"
        ;;
    $ERROR_KIND__ALIAS_NOT_ALLOWED_KEYWORD_RESERVED)
        shift 1
        message="alias not allowed, keywords [ $* ] are reserved"
        ;;
    $ERROR_KIND__ALIAS_NOT_ALLOWED_NAME_MALFORMED)
        shift 1
        message="alias not allowed, characters [ $* ] may not be in the name"
        ;;
    *)
        message="undefined error"
        ;;
    esac
    echo $message 1>&2
}

join_list_on() {
    local IFS=$1
    shift 1
    echo "$*"
}

get_wd_entries() {
    local IFS=" "
    echo $(cat $WD_FULL_PATH)
}

get_wd_aliases() {
    local aliases=()
    for entry in $(get_wd_entries); do
        local IFS="|"
        read -ra split_entry <<< "$entry"
        aliases+="${split_entry[0]} "
    done
    echo $aliases
}

find_entry_by_alias() {
    local val=""
    for entry in $(get_wd_entries); do
        local IFS="|"
        read -ra split_entry <<< "$entry"
        if [ "$1" == "${split_entry[0]}" ]; then
            val=$entry
            break;
        fi
    done
    echo $val
}

alias_exist() {
    local entry=$(find_entry_by_alias $1)
    if [ "$entry" != "" ]; then
        echo 1
    else
        echo 0
    fi
}

contains_bad_characters() {
    local is_bad=0
    for c in ${BAD_CHARACTERS[@]}; do
        if [[ "$1" =~ .*"$c".* ]]; then
            is_bad=1
            break;
        fi
    done
    echo $is_bad
}

is_reserved_keyword() {
    local reserved=0
    for cmd in ${WD_COMMANDS[@]}; do
        if [ "$1" == "$cmd" ]; then
            reserved=1
            break;
        fi
    done
    echo $reserved
}

goto_alias_target() {
    local entry=$(find_entry_by_alias $1)
    read -ra split_entry <<< "$entry"
    if [ "$entry" != "" ]; then
        local target=${split_entry[1]}
        if [ "$PWD" != "$target" ]; then
            export WD_PREV_PWD=($PWD $target)
        fi
        cd $target
    fi
}

handle_remove() {
    local wd_prompted=1
    local filtered_entries=()
    while [ $wd_prompted -eq 1 ]; do
        read -p "are you sure you want to remove alias [ $1 ]? (N/y) " user_input
        if [ "$user_input" == "" -o "${user_input,,}" == "n" ]; then
            echo "nothing changed"
            wd_prompted=0
        elif [ "${user_input,,}" == "y" ]; then
            for entry in $(get_wd_entries); do
                local IFS="|"
                read -ra split_entry <<< "$entry"
                if [ "$1" != "${split_entry[0]}" ]; then
                    filtered_entries+="$entry "
                fi
            done
            local IFS=" "
            if [ "$filtered_entries" ]; then
                echo $(join_list_on $'\n' $filtered_entries) > $WD_FULL_PATH
            else
                echo -n "" > $WD_FULL_PATH
            fi
            wd_prompted=0
        fi
    done
}

handle_rename() {
    local filtered_entries=()
    for entry in $(get_wd_entries); do
        local IFS="|"
        read -ra split_entry <<< "$entry"
        if [ "$1" == "${split_entry[0]}" ]; then
            filtered_entries+="$2|${split_entry[1]} "
        else
            filtered_entries+="$entry "
        fi
    done
    local IFS=" "
    echo $(join_list_on $'\n' $filtered_entries) > $WD_FULL_PATH
}

check_autocomplete() {
    if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion -o -f /etc/bash_completion ]; then
            complete -W "$(join_list_on " " ${WD_COMMANDS[@]}) $(get_wd_aliases) $(find . -maxdepth 1 -type d)" wd
        fi
    fi
}

check_autocomplete
